name: build and test
on: [push]

jobs:
  buildAndTest:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [18.x]

      steps: # Шаги выполнения
      - uses: actions/checkout@v1 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm ci
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting scss
        run: lint:scss
      - name: unit testing
        run: npm run test:unit